### ISSUE TITLE
HTTPS Calls to ClubReady

### ISSUE THREAD

**Issue by ChrisHammond** [BaReinhard/ClubReady-Checkin-React-Component#1]
FYI, we're going to be announcing, in the near future, a requirement to move all API requests to HTTPS, notice that some of your URLs are coded with HTTP://

If you update them now, you shouldn't have any issues.

We've yet to determine when we'll be sunsetting the HTTP calls, but wanted to give you a heads up.

Chris

**Comment by BaReinhard** [comment]
Thanks for the heads up Chris. I'm no longer with my previous employer so I don't have access to ClubReady anymore so I probably can't do any testing for this, but Ill be sure to update the urls at the very least

**Comment by ChrisHammond** [comment]
Thanks, hope all is well!
